apiVersion: v1
kind: Namespace
metadata:
  name: vvenegas
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: curso-devops-config
  namespace: vvenegas
data:
  USERNAME: "cmd"
  ENDPOINT: "http://api.google.com/v1"
---
apiVersion: v1
kind: Secret
metadata:
  name: curso-devops-secret
  namespace: vvenegas
type: Opaque
stringData:
  APIKEY: "123456789abcde"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: curso-devops-deployment
  namespace: vvenegas
  labels:
    app: curso-devops-stack-lab3
spec:
  replicas: 3
  selector:
    matchLabels:
      app: curso-devops-stack-lab3
  template:
    metadata:
      labels:
        app: curso-devops-stack-lab3
    spec:
      containers:
      - name: contenedor-lab3-vvf
        image: vnvenega/lab3-devops-vvf
        imagePullPolicy: Always
        env:
        - name: NODE_ENV
          value: development
        - name: PORT
          value: "3000"
        - name: USERNAME
          valueFrom:
            configMapKeyRef:
              name: curso-devops-config
              key: USERNAME
              optional: true
        - name: APIKEY
          valueFrom:
            secretKeyRef:
              name: curso-devops-secret
              key: APIKEY
              optional: true
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: curso-devops-service
  namespace: vvenegas
  labels:
    app: curso-devops-stack-lab3
spec:
  selector:
     app: curso-devops-stack-lab3
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000